version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=wedevs
      - POSTGRES_PASSWORD=iOdIICh2PAklbB
      - POSTGRES_DB=webdevsdb
    ports:
      - '5432:5432'
    volumes:
      - ./db-data/:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data
volumes:
  db:
    driver: local
  redis:
    driver: local